# Generated by Django 4.2.4 on 2023-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_remove_word_last_repeat_alter_word_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrepeat',
            name='repeat',
            field=models.IntegerField(default=0),
        ),
    ]
