# Generated by Django 4.2.4 on 2023-08-31 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('interested_area1', models.CharField(blank=True, max_length=20)),
                ('interested_area2', models.CharField(blank=True, max_length=20)),
                ('daily_goal', models.IntegerField(default=3)),
                ('premium', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, upload_to='user/picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
