# Generated by Django 4.2.4 on 2023-09-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
